// JavaScript Document

// marásminták
function mintA1() {document.getElementById('minta').innerHTML="<img src='mintak/A1.png' />";} 
function mintv1() {document.getElementById('minta').innerHTML="<img src='mintak/v01.png' />";} 
function mintv2() {document.getElementById('minta').innerHTML="<img src='mintak/v02.png' />";}
function mintv3() {document.getElementById('minta').innerHTML="<img src='mintak/v03.png' />";} 
function mintv4() {document.getElementById('minta').innerHTML="<img src='mintak/v04.png' />";}
function mintv5() {document.getElementById('minta').innerHTML="<img src='mintak/v05.png' />";} 
function mintv6() {document.getElementById('minta').innerHTML="<img src='mintak/v06.png' />";} 
function mintv7() {document.getElementById('minta').innerHTML="<img src='mintak/v07.png' />";}
function mintv8() {document.getElementById('minta').innerHTML="<img src='mintak/v08.png' />";} 
function mintv9() {document.getElementById('minta').innerHTML="<img src='mintak/v09.png' />";}
function mintv10() {document.getElementById('minta').innerHTML="<img src='mintak/v10.png' />";} 
function mintv11() {document.getElementById('minta').innerHTML="<img src='mintak/v11.png' />";}
function mint01() {document.getElementById('minta').innerHTML="<img src='mintak/001.png' />";}
function mint02() {document.getElementById('minta').innerHTML="<img src='mintak/002.png' />";}
function mint03() {document.getElementById('minta').innerHTML="<img src='mintak/003.png' />";}
function mint04() {document.getElementById('minta').innerHTML="<img src='mintak/004.png' />";}
function mint05() {document.getElementById('minta').innerHTML="<img src='mintak/005.png' />";}
function mint06() {document.getElementById('minta').innerHTML="<img src='mintak/006.png' />";}
function mint07() {document.getElementById('minta').innerHTML="<img src='mintak/007.png' />";}
function mint08() {document.getElementById('minta').innerHTML="<img src='mintak/008.png' />";} 
function mint09() {document.getElementById('minta').innerHTML="<img src='mintak/009.png' />";} 
function mint10() {document.getElementById('minta').innerHTML="<img src='mintak/010.png' />";} 
function mint11() {document.getElementById('minta').innerHTML="<img src='mintak/011.png' />";} 
function mint12() {document.getElementById('minta').innerHTML="<img src='mintak/012.png' />";} 
function mint13() {document.getElementById('minta').innerHTML="<img src='mintak/013.png' />";}
function mint14() {document.getElementById('minta').innerHTML="<img src='mintak/014.png' />";} 
function mint15() {document.getElementById('minta').innerHTML="<img src='mintak/015.png' />";} 
function mint16() {document.getElementById('minta').innerHTML="<img src='mintak/016.png' />";} 
function mint17() {document.getElementById('minta').innerHTML="<img src='mintak/017.png' />";} 
function mint18() {document.getElementById('minta').innerHTML="<img src='mintak/018.png' />";} 
function mint19() {document.getElementById('minta').innerHTML="<img src='mintak/019.png' />";} 
function mint20() {document.getElementById('minta').innerHTML="<img src='mintak/020.png' />";}
function mint21() {document.getElementById('minta').innerHTML="<img src='mintak/021.png' />";}
function mint22() {document.getElementById('minta').innerHTML="<img src='mintak/022.png' />";}
function mint23() {document.getElementById('minta').innerHTML="<img src='mintak/023.png' />";}
function mint24() {document.getElementById('minta').innerHTML="<img src='mintak/024.png' />";}
function mint25() {document.getElementById('minta').innerHTML="<img src='mintak/025.png' />";}
function mint26() {document.getElementById('minta').innerHTML="<img src='mintak/026.png' />";}
function mint27() {document.getElementById('minta').innerHTML="<img src='mintak/027.png' />";}
function mint28() {document.getElementById('minta').innerHTML="<img src='mintak/028.png' />";}
function mint29() {document.getElementById('minta').innerHTML="<img src='mintak/029.png' />";}
function mint30() {document.getElementById('minta').innerHTML="<img src='mintak/030.png' />";}
function mint31() {document.getElementById('minta').innerHTML="<img src='mintak/031.png' />";}
function mint32() {document.getElementById('minta').innerHTML="<img src='mintak/032.png' />";}
function mint33() {document.getElementById('minta').innerHTML="<img src='mintak/033.png' />";}
function mint34() {document.getElementById('minta').innerHTML="<img src='mintak/034.png' />";}
function mint35() {document.getElementById('minta').innerHTML="<img src='mintak/035.png' />";}
function mint36() {document.getElementById('minta').innerHTML="<img src='mintak/036.png' />";}
function mint37() {document.getElementById('minta').innerHTML="<img src='mintak/037.png' />";}
function mint38() {document.getElementById('minta').innerHTML="<img src='mintak/038.png' />";}
function mint39() {document.getElementById('minta').innerHTML="<img src='mintak/039.png' />";}
function mint40() {document.getElementById('minta').innerHTML="<img src='mintak/040.png' />";}
function mint41() {document.getElementById('minta').innerHTML="<img src='mintak/041.png' />";}
function mint42() {document.getElementById('minta').innerHTML="<img src='mintak/042.png' />";}
function mint43() {document.getElementById('minta').innerHTML="<img src='mintak/043.png' />";}
function mint44() {document.getElementById('minta').innerHTML="<img src='mintak/044.png' />";}
function mint45() {document.getElementById('minta').innerHTML="<img src='mintak/045.png' />";}
function mint46() {document.getElementById('minta').innerHTML="<img src='mintak/046.png' />";}
function mint47() {document.getElementById('minta').innerHTML="<img src='mintak/047.png' />";}
function mint48() {document.getElementById('minta').innerHTML="<img src='mintak/048.png' />";}
function mint49() {document.getElementById('minta').innerHTML="<img src='mintak/049.png' />";}
function mint50() {document.getElementById('minta').innerHTML="<img src='mintak/050.png' />";}
function mint51() {document.getElementById('minta').innerHTML="<img src='mintak/051.png' />";}
function mint52() {document.getElementById('minta').innerHTML="<img src='mintak/052.png' />";}
function mint53() {document.getElementById('minta').innerHTML="<img src='mintak/053.png' />";}
function mint54() {document.getElementById('minta').innerHTML="<img src='mintak/054.png' />";}
function mint55() {document.getElementById('minta').innerHTML="<img src='mintak/055.png' />";}
function mint56() {document.getElementById('minta').innerHTML="<img src='mintak/056.png' />";}
function mint57() {document.getElementById('minta').innerHTML="<img src='mintak/057.png' />";}
function mint58() {document.getElementById('minta').innerHTML="<img src='mintak/058.png' />";}
function mint59() {document.getElementById('minta').innerHTML="<img src='mintak/059.png' />";}
function mint60() {document.getElementById('minta').innerHTML="<img src='mintak/060.png' />";}
function mint61() {document.getElementById('minta').innerHTML="<img src='mintak/061.png' />";}
function mint62() {document.getElementById('minta').innerHTML="<img src='mintak/062.png' />";}
function mint63() {document.getElementById('minta').innerHTML="<img src='mintak/063.png' />";}
function mint64() {document.getElementById('minta').innerHTML="<img src='mintak/064.png' />";}
function mint65() {document.getElementById('minta').innerHTML="<img src='mintak/065.png' />";}
function mint66() {document.getElementById('minta').innerHTML="<img src='mintak/066.png' />";}
function mint67() {document.getElementById('minta').innerHTML="<img src='mintak/067.png' />";}
function mint68() {document.getElementById('minta').innerHTML="<img src='mintak/068.png' />";}
function mint69() {document.getElementById('minta').innerHTML="<img src='mintak/069.png' />";}
function mint70() {document.getElementById('minta').innerHTML="<img src='mintak/070.png' />";}
function mint71() {document.getElementById('minta').innerHTML="<img src='mintak/071.png' />";}
function mint72() {document.getElementById('minta').innerHTML="<img src='mintak/072.png' />";}
function mint73() {document.getElementById('minta').innerHTML="<img src='mintak/073.png' />";}
function mint74() {document.getElementById('minta').innerHTML="<img src='mintak/074.png' />";}
function mint75() {document.getElementById('minta').innerHTML="<img src='mintak/075.png' />";}
function mint76() {document.getElementById('minta').innerHTML="<img src='mintak/076.png' />";}
function mint77() {document.getElementById('minta').innerHTML="<img src='mintak/077.png' />";}
function mint78() {document.getElementById('minta').innerHTML="<img src='mintak/078.png' />";}
function mint79() {document.getElementById('minta').innerHTML="<img src='mintak/079.png' />";}
function mint80() {document.getElementById('minta').innerHTML="<img src='mintak/080.png' />";}
function mint81() {document.getElementById('minta').innerHTML="<img src='mintak/081.png' />";}
function mint82() {document.getElementById('minta').innerHTML="<img src='mintak/082.png' />";}
function mint83() {document.getElementById('minta').innerHTML="<img src='mintak/083.png' />";}
function mint84() {document.getElementById('minta').innerHTML="<img src='mintak/084.png' />";}
function mint85() {document.getElementById('minta').innerHTML="<img src='mintak/085.png' />";}
function mint86() {document.getElementById('minta').innerHTML="<img src='mintak/086.png' />";}
function mint87() {document.getElementById('minta').innerHTML="<img src='mintak/087.png' />";}
function mint88() {document.getElementById('minta').innerHTML="<img src='mintak/088.png' />";}
function mint89() {document.getElementById('minta').innerHTML="<img src='mintak/089.png' />";}
function mint90() {document.getElementById('minta').innerHTML="<img src='mintak/090.png' />";}
function mint91() {document.getElementById('minta').innerHTML="<img src='mintak/091.png' />";}
function mint92() {document.getElementById('minta').innerHTML="<img src='mintak/092.png' />";}
function mint93() {document.getElementById('minta').innerHTML="<img src='mintak/093.png' />";}
function mint94() {document.getElementById('minta').innerHTML="<img src='mintak/094.png' />";}
function mint95() {document.getElementById('minta').innerHTML="<img src='mintak/095.png' />";}
function mint96() {document.getElementById('minta').innerHTML="<img src='mintak/096.png' />";}
function mint97() {document.getElementById('minta').innerHTML="<img src='mintak/097.png' />";}
function mint98() {document.getElementById('minta').innerHTML="<img src='mintak/098.png' />";}
function mint99() {document.getElementById('minta').innerHTML="<img src='mintak/099.png' />";}
function mint100() {document.getElementById('minta').innerHTML="<img src='mintak/100.png' />";}
function mint101() {document.getElementById('minta').innerHTML="<img src='mintak/101.png' />";}
function mint102() {document.getElementById('minta').innerHTML="<img src='mintak/102.png' />";}
function mint103() {document.getElementById('minta').innerHTML="<img src='mintak/103.png' />";}
function mint104() {document.getElementById('minta').innerHTML="<img src='mintak/104.png' />";}
function mint105() {document.getElementById('minta').innerHTML="<img src='mintak/105.png' />";}
function mint106() {document.getElementById('minta').innerHTML="<img src='mintak/106.png' />";}
function mint107() {document.getElementById('minta').innerHTML="<img src='mintak/107.png' />";}
function mint108() {document.getElementById('minta').innerHTML="<img src='mintak/108.png' />";}
function mint109() {document.getElementById('minta').innerHTML="<img src='mintak/109.png' />";}
function mint110() {document.getElementById('minta').innerHTML="<img src='mintak/110.png' />";}
function mint111() {document.getElementById('minta').innerHTML="<img src='mintak/111.png' />";}
function mint112() {document.getElementById('minta').innerHTML="<img src='mintak/112.png' />";}
function mint113() {document.getElementById('minta').innerHTML="<img src='mintak/113.png' />";}
function mint114() {document.getElementById('minta').innerHTML="<img src='mintak/114.png' />";}
function mint115() {document.getElementById('minta').innerHTML="<img src='mintak/115.png' />";}
function mint116() {document.getElementById('minta').innerHTML="<img src='mintak/116.png' />";}
function mint117() {document.getElementById('minta').innerHTML="<img src='mintak/117.png' />";}
function mint118() {document.getElementById('minta').innerHTML="<img src='mintak/118.png' />";}
function mint119() {document.getElementById('minta').innerHTML="<img src='mintak/119.png' />";}
function mint120() {document.getElementById('minta').innerHTML="<img src='mintak/120.png' />";}
function mint121() {document.getElementById('minta').innerHTML="<img src='mintak/121.png' />";}
function mint122() {document.getElementById('minta').innerHTML="<img src='mintak/122.png' />";}
function mint123() {document.getElementById('minta').innerHTML="<img src='mintak/123.png' />";}
function mint124() {document.getElementById('minta').innerHTML="<img src='mintak/124.png' />";}
function mint125() {document.getElementById('minta').innerHTML="<img src='mintak/125.png' />";}
function mint126() {document.getElementById('minta').innerHTML="<img src='mintak/126.png' />";}
function mint127() {document.getElementById('minta').innerHTML="<img src='mintak/127.png' />";}
function mint128() {document.getElementById('minta').innerHTML="<img src='mintak/128.png' />";}
function mint129() {document.getElementById('minta').innerHTML="<img src='mintak/129.png' />";}
function mint130() {document.getElementById('minta').innerHTML="<img src='mintak/130.png' />";}
function mint131() {document.getElementById('minta').innerHTML="<img src='mintak/131.png' />";}
function mint132() {document.getElementById('minta').innerHTML="<img src='mintak/132.png' />";}

function mintA1u() {document.getElementById('minta').innerHTML="<img src='mintak/A1u.png' />";} 
function mintv1u() {document.getElementById('minta').innerHTML="<img src='mintak/v01u.png' />";} 
function mintv2u() {document.getElementById('minta').innerHTML="<img src='mintak/v02u.png' />";}
function mintv3u() {document.getElementById('minta').innerHTML="<img src='mintak/v03u.png' />";} 
function mintv4u() {document.getElementById('minta').innerHTML="<img src='mintak/v04u.png' />";}
function mintv5u() {document.getElementById('minta').innerHTML="<img src='mintak/v05u.png' />";} 
function mintv6u() {document.getElementById('minta').innerHTML="<img src='mintak/v06u.png' />";} 
function mintv7u() {document.getElementById('minta').innerHTML="<img src='mintak/v07u.png' />";}
function mintv8u() {document.getElementById('minta').innerHTML="<img src='mintak/v08u.png' />";} 
function mintv9u() {document.getElementById('minta').innerHTML="<img src='mintak/v09u.png' />";}
function mintv10u() {document.getElementById('minta').innerHTML="<img src='mintak/v10u.png' />";} 
function mintv11u() {document.getElementById('minta').innerHTML="<img src='mintak/v11u.png' />";}
function mint01u() {document.getElementById('minta').innerHTML="<img src='mintak/001u.png' />";}
function mint02u() {document.getElementById('minta').innerHTML="<img src='mintak/002u.png' />";}
function mint03u() {document.getElementById('minta').innerHTML="<img src='mintak/003u.png' />";}
function mint04u() {document.getElementById('minta').innerHTML="<img src='mintak/004u.png' />";}
function mint05u() {document.getElementById('minta').innerHTML="<img src='mintak/005u.png' />";}
function mint06u() {document.getElementById('minta').innerHTML="<img src='mintak/006u.png' />";}
function mint07u() {document.getElementById('minta').innerHTML="<img src='mintak/007u.png' />";}
function mint08u() {document.getElementById('minta').innerHTML="<img src='mintak/008u.png' />";} 
function mint09u() {document.getElementById('minta').innerHTML="<img src='mintak/009u.png' />";} 
function mint10u() {document.getElementById('minta').innerHTML="<img src='mintak/010u.png' />";} 
function mint11u() {document.getElementById('minta').innerHTML="<img src='mintak/011u.png' />";} 
function mint12u() {document.getElementById('minta').innerHTML="<img src='mintak/012u.png' />";} 
function mint13u() {document.getElementById('minta').innerHTML="<img src='mintak/013u.png' />";}
function mint14u() {document.getElementById('minta').innerHTML="<img src='mintak/014u.png' />";} 
function mint15u() {document.getElementById('minta').innerHTML="<img src='mintak/015u.png' />";} 
function mint16u() {document.getElementById('minta').innerHTML="<img src='mintak/016u.png' />";} 
function mint17u() {document.getElementById('minta').innerHTML="<img src='mintak/017u.png' />";} 
function mint18u() {document.getElementById('minta').innerHTML="<img src='mintak/018u.png' />";} 
function mint19u() {document.getElementById('minta').innerHTML="<img src='mintak/019u.png' />";} 
function mint20u() {document.getElementById('minta').innerHTML="<img src='mintak/020u.png' />";}
function mint21u() {document.getElementById('minta').innerHTML="<img src='mintak/021u.png' />";}
function mint22u() {document.getElementById('minta').innerHTML="<img src='mintak/022u.png' />";}
function mint23u() {document.getElementById('minta').innerHTML="<img src='mintak/023u.png' />";}
function mint24u() {document.getElementById('minta').innerHTML="<img src='mintak/024u.png' />";}
function mint25u() {document.getElementById('minta').innerHTML="<img src='mintak/025u.png' />";}
function mint26u() {document.getElementById('minta').innerHTML="<img src='mintak/026u.png' />";}
function mint27u() {document.getElementById('minta').innerHTML="<img src='mintak/027u.png' />";}
function mint28u() {document.getElementById('minta').innerHTML="<img src='mintak/028u.png' />";}
function mint29u() {document.getElementById('minta').innerHTML="<img src='mintak/029u.png' />";}
function mint30u() {document.getElementById('minta').innerHTML="<img src='mintak/030u.png' />";}
function mint31u() {document.getElementById('minta').innerHTML="<img src='mintak/031u.png' />";}
function mint32u() {document.getElementById('minta').innerHTML="<img src='mintak/032u.png' />";}
function mint33u() {document.getElementById('minta').innerHTML="<img src='mintak/033u.png' />";}
function mint34u() {document.getElementById('minta').innerHTML="<img src='mintak/034u.png' />";}
function mint35u() {document.getElementById('minta').innerHTML="<img src='mintak/035u.png' />";}
function mint36u() {document.getElementById('minta').innerHTML="<img src='mintak/036u.png' />";}
function mint37u() {document.getElementById('minta').innerHTML="<img src='mintak/037u.png' />";}
function mint38u() {document.getElementById('minta').innerHTML="<img src='mintak/038u.png' />";}
function mint39u() {document.getElementById('minta').innerHTML="<img src='mintak/039u.png' />";}
function mint40u() {document.getElementById('minta').innerHTML="<img src='mintak/040u.png' />";}
function mint41u() {document.getElementById('minta').innerHTML="<img src='mintak/041u.png' />";}
function mint42u() {document.getElementById('minta').innerHTML="<img src='mintak/042u.png' />";}
function mint43u() {document.getElementById('minta').innerHTML="<img src='mintak/043u.png' />";}
function mint44u() {document.getElementById('minta').innerHTML="<img src='mintak/044u.png' />";}
function mint45u() {document.getElementById('minta').innerHTML="<img src='mintak/045u.png' />";}
function mint46u() {document.getElementById('minta').innerHTML="<img src='mintak/046u.png' />";}
function mint47u() {document.getElementById('minta').innerHTML="<img src='mintak/047u.png' />";}
function mint48u() {document.getElementById('minta').innerHTML="<img src='mintak/048u.png' />";}
function mint49u() {document.getElementById('minta').innerHTML="<img src='mintak/049u.png' />";}
function mint50u() {document.getElementById('minta').innerHTML="<img src='mintak/050u.png' />";}
function mint51u() {document.getElementById('minta').innerHTML="<img src='mintak/051u.png' />";}
function mint52u() {document.getElementById('minta').innerHTML="<img src='mintak/052u.png' />";}
function mint53u() {document.getElementById('minta').innerHTML="<img src='mintak/053u.png' />";}
function mint54u() {document.getElementById('minta').innerHTML="<img src='mintak/054u.png' />";}
function mint55u() {document.getElementById('minta').innerHTML="<img src='mintak/055u.png' />";}
function mint56u() {document.getElementById('minta').innerHTML="<img src='mintak/056u.png' />";}
function mint57u() {document.getElementById('minta').innerHTML="<img src='mintak/057u.png' />";}
function mint58u() {document.getElementById('minta').innerHTML="<img src='mintak/058u.png' />";}
function mint59u() {document.getElementById('minta').innerHTML="<img src='mintak/059u.png' />";}
function mint60u() {document.getElementById('minta').innerHTML="<img src='mintak/060u.png' />";}
function mint61u() {document.getElementById('minta').innerHTML="<img src='mintak/061u.png' />";}
function mint62u() {document.getElementById('minta').innerHTML="<img src='mintak/062u.png' />";}
function mint63u() {document.getElementById('minta').innerHTML="<img src='mintak/063u.png' />";}
function mint64u() {document.getElementById('minta').innerHTML="<img src='mintak/064u.png' />";}
function mint65u() {document.getElementById('minta').innerHTML="<img src='mintak/065u.png' />";}
function mint66u() {document.getElementById('minta').innerHTML="<img src='mintak/066u.png' />";}
function mint67u() {document.getElementById('minta').innerHTML="<img src='mintak/067u.png' />";}
function mint68u() {document.getElementById('minta').innerHTML="<img src='mintak/068u.png' />";}
function mint69u() {document.getElementById('minta').innerHTML="<img src='mintak/069u.png' />";}
function mint70u() {document.getElementById('minta').innerHTML="<img src='mintak/070u.png' />";}
function mint71u() {document.getElementById('minta').innerHTML="<img src='mintak/071u.png' />";}
function mint72u() {document.getElementById('minta').innerHTML="<img src='mintak/072u.png' />";}
function mint73u() {document.getElementById('minta').innerHTML="<img src='mintak/073u.png' />";}
function mint74u() {document.getElementById('minta').innerHTML="<img src='mintak/074u.png' />";}
function mint75u() {document.getElementById('minta').innerHTML="<img src='mintak/075u.png' />";}
function mint76u() {document.getElementById('minta').innerHTML="<img src='mintak/076u.png' />";}
function mint77u() {document.getElementById('minta').innerHTML="<img src='mintak/077u.png' />";}
function mint78u() {document.getElementById('minta').innerHTML="<img src='mintak/078u.png' />";}
function mint79u() {document.getElementById('minta').innerHTML="<img src='mintak/079u.png' />";}
function mint80u() {document.getElementById('minta').innerHTML="<img src='mintak/080u.png' />";}
function mint81u() {document.getElementById('minta').innerHTML="<img src='mintak/081u.png' />";}
function mint82u() {document.getElementById('minta').innerHTML="<img src='mintak/082u.png' />";}
function mint83u() {document.getElementById('minta').innerHTML="<img src='mintak/083u.png' />";}
function mint84u() {document.getElementById('minta').innerHTML="<img src='mintak/084u.png' />";}
function mint85u() {document.getElementById('minta').innerHTML="<img src='mintak/085u.png' />";}
function mint86u() {document.getElementById('minta').innerHTML="<img src='mintak/086u.png' />";}
function mint87u() {document.getElementById('minta').innerHTML="<img src='mintak/087u.png' />";}
function mint88u() {document.getElementById('minta').innerHTML="<img src='mintak/088u.png' />";}
function mint89u() {document.getElementById('minta').innerHTML="<img src='mintak/089u.png' />";}
function mint90u() {document.getElementById('minta').innerHTML="<img src='mintak/090u.png' />";}
function mint91u() {document.getElementById('minta').innerHTML="<img src='mintak/091u.png' />";}
function mint92u() {document.getElementById('minta').innerHTML="<img src='mintak/092u.png' />";}
function mint93u() {document.getElementById('minta').innerHTML="<img src='mintak/093u.png' />";}
function mint94u() {document.getElementById('minta').innerHTML="<img src='mintak/094u.png' />";}
function mint95u() {document.getElementById('minta').innerHTML="<img src='mintak/095u.png' />";}
function mint96u() {document.getElementById('minta').innerHTML="<img src='mintak/096u.png' />";}
function mint97u() {document.getElementById('minta').innerHTML="<img src='mintak/097u.png' />";}
function mint98u() {document.getElementById('minta').innerHTML="<img src='mintak/098u.png' />";}
function mint99u() {document.getElementById('minta').innerHTML="<img src='mintak/099u.png' />";}
function mint100u() {document.getElementById('minta').innerHTML="<img src='mintak/100u.png' />";}
function mint101u() {document.getElementById('minta').innerHTML="<img src='mintak/101u.png' />";}
function mint102u() {document.getElementById('minta').innerHTML="<img src='mintak/102u.png' />";}
function mint103u() {document.getElementById('minta').innerHTML="<img src='mintak/103u.png' />";}
function mint104u() {document.getElementById('minta').innerHTML="<img src='mintak/104u.png' />";}
function mint105u() {document.getElementById('minta').innerHTML="<img src='mintak/105u.png' />";}
function mint106u() {document.getElementById('minta').innerHTML="<img src='mintak/106u.png' />";}
function mint107u() {document.getElementById('minta').innerHTML="<img src='mintak/107u.png' />";}
function mint108u() {document.getElementById('minta').innerHTML="<img src='mintak/108u.png' />";}
function mint109u() {document.getElementById('minta').innerHTML="<img src='mintak/109u.png' />";}
function mint110u() {document.getElementById('minta').innerHTML="<img src='mintak/110u.png' />";}
function mint111u() {document.getElementById('minta').innerHTML="<img src='mintak/111u.png' />";}
function mint112u() {document.getElementById('minta').innerHTML="<img src='mintak/112u.png' />";}
function mint113u() {document.getElementById('minta').innerHTML="<img src='mintak/113u.png' />";}
function mint114u() {document.getElementById('minta').innerHTML="<img src='mintak/114u.png' />";}
function mint115u() {document.getElementById('minta').innerHTML="<img src='mintak/115u.png' />";}
function mint116u() {document.getElementById('minta').innerHTML="<img src='mintak/116u.png' />";}
function mint117u() {document.getElementById('minta').innerHTML="<img src='mintak/117u.png' />";}
function mint118u() {document.getElementById('minta').innerHTML="<img src='mintak/118u.png' />";}
function mint119u() {document.getElementById('minta').innerHTML="<img src='mintak/119u.png' />";}
function mint120u() {document.getElementById('minta').innerHTML="<img src='mintak/120u.png' />";}
function mint121u() {document.getElementById('minta').innerHTML="<img src='mintak/121u.png' />";}
function mint122u() {document.getElementById('minta').innerHTML="<img src='mintak/122u.png' />";}
function mint123u() {document.getElementById('minta').innerHTML="<img src='mintak/123u.png' />";}
function mint124u() {document.getElementById('minta').innerHTML="<img src='mintak/124u.png' />";}
function mint125u() {document.getElementById('minta').innerHTML="<img src='mintak/125u.png' />";}
function mint126u() {document.getElementById('minta').innerHTML="<img src='mintak/126u.png' />";}
function mint127u() {document.getElementById('minta').innerHTML="<img src='mintak/127u.png' />";}
function mint128u() {document.getElementById('minta').innerHTML="<img src='mintak/128u.png' />";}
function mint129u() {document.getElementById('minta').innerHTML="<img src='mintak/129u.png' />";}
function mint130u() {document.getElementById('minta').innerHTML="<img src='mintak/130u.png' />";}
function mint131u() {document.getElementById('minta').innerHTML="<img src='mintak/131u.png' />";}
function mint132u() {document.getElementById('minta').innerHTML="<img src='mintak/132u.png' />";}


//alap színek
function foila1() {document.getElementById('folia').innerHTML="<img src='folia/s1.png' />";} 
function foila3() {document.getElementById('folia').innerHTML="<img src='folia/s2.png' />";}
function foila4() {document.getElementById('folia').innerHTML="<img src='folia/s3.png' />";} 
function foila5() {document.getElementById('folia').innerHTML="<img src='folia/s4.png' />";}
function foila6() {document.getElementById('folia').innerHTML="<img src='folia/s5.png' />";} 
function foila7() {document.getElementById('folia').innerHTML="<img src='folia/s6.png' />";}
function foila9() {document.getElementById('folia').innerHTML="<img src='folia/s7.png' />";} 
function foila13() {document.getElementById('folia').innerHTML="<img src='folia/s8.png' />";}
function foilb64() {document.getElementById('folia').innerHTML="<img src='folia/s9.png' />";}
function foilb65() {document.getElementById('folia').innerHTML="<img src='folia/s10.png' />";} 
function foilb66() {document.getElementById('folia').innerHTML="<img src='folia/s11.png' />";} 
function foilb67() {document.getElementById('folia').innerHTML="<img src='folia/s12.png' />";} 
function foilb68() {document.getElementById('folia').innerHTML="<img src='folia/s13.png' />";} 
function foilb69() {document.getElementById('folia').innerHTML="<img src='folia/s14.png' />";} 
function foilb70() {document.getElementById('folia').innerHTML="<img src='folia/s15.png' />";} 
function foilb71() {document.getElementById('folia').innerHTML="<img src='folia/r1.png' />";} 
function foilb72() {document.getElementById('folia').innerHTML="<img src='folia/r2.png' />";} 
function foilb73() {document.getElementById('folia').innerHTML="<img src='folia/r3.png' />";} 
function foilb74() {document.getElementById('folia').innerHTML="<img src='folia/r4.png' />";} 
function foilb75() {document.getElementById('folia').innerHTML="<img src='folia/r5.png' />";} 
function foilb76() {document.getElementById('folia').innerHTML="<img src='folia/r6.png' />";} 
function foilb77() {document.getElementById('folia').innerHTML="<img src='folia/r7.png' />";} 
function foilb79() {document.getElementById('folia').innerHTML="<img src='folia/r8.png' />";} 
function foilb81() {document.getElementById('folia').innerHTML="<img src='folia/r9.png' />";} 
function foilb83() {document.getElementById('folia').innerHTML="<img src='folia/r10.png' />";} 
function foilb84() {document.getElementById('folia').innerHTML="<img src='folia/r11.png' />";} 
function foilb85() {document.getElementById('folia').innerHTML="<img src='folia/r12.png' />";} 
function foilb86() {document.getElementById('folia').innerHTML="<img src='folia/r13.png' />";} 
function foilb87() {document.getElementById('folia').innerHTML="<img src='folia/r14.png' />";} 
function foilb88() {document.getElementById('folia').innerHTML="<img src='folia/r15.png' />";} 
function foilb89() {document.getElementById('folia').innerHTML="<img src='folia/r16.png' />";} 
function foilb90() {document.getElementById('folia').innerHTML="<img src='folia/r17.png' />";} 
function foilb91() {document.getElementById('folia').innerHTML="<img src='folia/r18.png' />";} 
function foilb92() {document.getElementById('folia').innerHTML="<img src='folia/r19.png' />";} 
function foilb93() {document.getElementById('folia').innerHTML="<img src='folia/r20.png' />";} 
function foilb94() {document.getElementById('folia').innerHTML="<img src='folia/r21.png' />";} 
function foilb121() {document.getElementById('folia').innerHTML="<img src='folia/r22.png' />";} 
function foilb122() {document.getElementById('folia').innerHTML="<img src='folia/r23.png' />";} 
function foilb123() {document.getElementById('folia').innerHTML="<img src='folia/r24.png' />";} 
function foilb126() {document.getElementById('folia').innerHTML="<img src='folia/r25.png' />";} 
function foilb127() {document.getElementById('folia').innerHTML="<img src='folia/r26.png' />";} 
function foilb128() {document.getElementById('folia').innerHTML="<img src='folia/r27.png' />";} 
function foilb129() {document.getElementById('folia').innerHTML="<img src='folia/r28.png' />";} 
function foilb130() {document.getElementById('folia').innerHTML="<img src='folia/r29.png' />";} 
function foilb140() {document.getElementById('folia').innerHTML="<img src='folia/r30.png' />";} 
function foilb141() {document.getElementById('folia').innerHTML="<img src='folia/r31.png' />";} 
function foilb142() {document.getElementById('folia').innerHTML="<img src='folia/r32.png' />";} 
function foilb143() {document.getElementById('folia').innerHTML="<img src='folia/r33.png' />";} 
function foilb200() {document.getElementById('folia').innerHTML="<img src='folia/r34.png' />";} 
function foilb201() {document.getElementById('folia').innerHTML="<img src='folia/r35.png' />";} 
function foilb202() {document.getElementById('folia').innerHTML="<img src='folia/r36.png' />";} 
function foilb203() {document.getElementById('folia').innerHTML="<img src='folia/r37.png' />";}
function foilb204() {document.getElementById('folia').innerHTML="<img src='folia/r38.png' />";} 
function foilb205() {document.getElementById('folia').innerHTML="<img src='folia/r39.png' />";} 
function foilc10() {document.getElementById('folia').innerHTML="<img src='folia/r40.png' />";} 
function foilc11() {document.getElementById('folia').innerHTML="<img src='folia/r41.png' />";} 
function foilc12() {document.getElementById('folia').innerHTML="<img src='folia/r42.png' />";} 
function foilc13() {document.getElementById('folia').innerHTML="<img src='folia/r43.png' />";} 
function foilc14() {document.getElementById('folia').innerHTML="<img src='folia/r44.png' />";} 
function foilc15() {document.getElementById('folia').innerHTML="<img src='folia/r45.png' />";} 
function foilc17() {document.getElementById('folia').innerHTML="<img src='folia/r46.png' />";} 
function foilc18() {document.getElementById('folia').innerHTML="<img src='folia/r47.png' />";} 
function foilc19() {document.getElementById('folia').innerHTML="<img src='folia/r48.png' />";} 
function foilc20() {document.getElementById('folia').innerHTML="<img src='folia/r49.png' />";} 
function foilc21() {document.getElementById('folia').innerHTML="<img src='folia/r50.png' />";} 
function foilc22() {document.getElementById('folia').innerHTML="<img src='folia/r51.png' />";} 
function foilc63() {document.getElementById('folia').innerHTML="<img src='folia/r52.png' />";} 
function foilnat() {document.getElementById('folia').innerHTML="<img src='folia/r53.png' />";} 



//vasalat
function vas() 	{document.getElementById('vashatter').innerHTML="<img src='vasalat/vas.png' />";}

//tokalap
function alap() 	{document.getElementById('alap').innerHTML="<img src='mintak/tok.png' />";}
function tok2() 	{document.getElementById('alap').innerHTML="<img src='mintak/tok2.png' />";}
function pant() 	{document.getElementById('pant').innerHTML="<img src='vasalat/pant.png' />";}

		$( document).ready(function(){
	$("#frame4 a:nth-child(4)").addClass("active");
	$("#frame3 a:nth-child(10)").addClass("active");
	$("#frame5 a:nth-child(4)").addClass("active");
	
	
	
});
